### PR TITLE
Enables liberasurecode_rs_vand

### PR DESCRIPTION
**Pull request by shinnya**
It's convenient for debugging.

### CODE REVIEW

**Comment by yuezato** [comment]
LGTM

**Comment by yuezato** [comment]
LGTM

**Review by yuezato — APPROVED** [review]

**Review by sile — APPROVED** [review]
LGTM

**Comment by yuezato** [comment]
We have adopted this change on the `dyn` branch
https://github.com/frugalos/liberasurecode/commit/149a047368aed89f08a6ed3f2afa4beafa40832d

**Pull request closed without merging**
